### ISSUE TITLE
Odoo Framework

### ISSUE THREAD

**Issue by wonderfan** [wonderfan/python#18]
The office site is https://www.odoo.com/

The code repo is @odoo

**Comment by wonderfan** [comment]
@daihang

**Comment by daihang** [comment]
seems like SAP in cloud, but more lightweight?

**Comment by wonderfan** [comment]
Yes. it is popular open source project. It definitely solves the modern-ERP requirement for SM enterprises.

**Comment by daihang** [comment]
Let me try if I can reply with mail client directly

**Comment by wonderfan** [comment]
It works through email reply
